# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

indiv_sim_cpp <- function(args) {
    .Call('_covfefe_indiv_sim_cpp', PACKAGE = 'covfefe', args)
}

draw_hosts_cpp <- function(infection_history, args) {
    .Call('_covfefe_draw_hosts_cpp', PACKAGE = 'covfefe', infection_history, args)
}

prune_cpp <- function(infection_history, samp_hosts_raw, args) {
    .Call('_covfefe_prune_cpp', PACKAGE = 'covfefe', infection_history, samp_hosts_raw, args)
}

sim_genotypes_cpp <- function(samp_hosts_raw, args) {
    .Call('_covfefe_sim_genotypes_cpp', PACKAGE = 'covfefe', samp_hosts_raw, args)
}

