# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

indiv_sim_cpp <- function(args) {
    .Call('_covfefe_indiv_sim_cpp', PACKAGE = 'covfefe', args)
}

sim_genotypes_cpp <- function(line_list, args) {
    .Call('_covfefe_sim_genotypes_cpp', PACKAGE = 'covfefe', line_list, args)
}

